### ISSUE TITLE
本地Git 工程启动之后,会出现这个报错信息

### ISSUE THREAD

**Issue by Dssssds** [sparrow-js/an-codeAI#78]
<img width="1484" alt="image" src="https://github.com/sparrow-js/an-codeAI/assets/17268259/835d9afb-dbfa-49d9-81f9-9ccc49be76ca">

node version : 18.17.0
npm 安装

**Comment by sparrow-js** [comment]
excalidraw 版本引起的报错，可以版本固定在0.17.2，或者自己升级下

**Comment by Dssssds** [comment]
好的, 感谢.

**Comment by Dssssds** [comment]
确实,node_modules 的版本是 0.17.3了.
