### ISSUE TITLE
Unhandled Runtime Error  ChunkLoadError: Loading chunk vendor failed. i have installed everything latest in alpine container and getting this error which is related to excalidraw i guess so any fixes for it?

### ISSUE THREAD

**Issue by HakaishinShwet** [sparrow-js/an-codeAI#85]
Unhandled Runtime Error

ChunkLoadError: Loading chunk vendor failed.
(error: [http://localhost:2229/excalidraw-assets-dev/vendor-1e45dd9aba63a718dcee.js)](http://localhost:2229/excalidraw-assets-dev/vendor-1e45dd9aba63a718dcee.js)
Call Stack
__nested_webpack_require_9336666__.f.j
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5817:0)
__nested_webpack_require_9336666__.e/<
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5696:32)
__nested_webpack_require_9336666__.e
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5695:62)
<unknown>
webpack-internal:///../../../node_modules/browser-fs-access/dist/index.mjs (49:238)
../../../node_modules/browser-fs-access/dist/index.mjs
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5568:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../data/filesystem.ts (7:94)
../../data/filesystem.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (3764:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../data/json.ts (11:88)
../../data/json.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (3797:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../scene/export.ts (13:87)
../../scene/export.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4545:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../utils.ts (27:90)
../utils.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4380:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../frame.ts (38:92)
../../frame.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4116:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../scene/selection.ts (14:83)
../../scene/selection.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4589:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../scene/Scene.ts (7:87)
../../scene/Scene.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4501:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../element/mutateElement.ts (7:89)
../../element/mutateElement.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (3973:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../element/sizeHelpers.ts (10:91)
../../element/sizeHelpers.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4028:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../element/index.ts (51:89)
../../element/index.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (3951:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../scene/scrollbars.ts (9:85)
../../scene/scrollbars.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4578:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../scene/index.ts (19:88)
../../scene/index.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4556:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../actions/actionDeleteSelected.tsx (6:83)
../../actions/actionDeleteSelected.tsx
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (2147:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../actions/index.ts (67:98)
../../actions/index.ts
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (2389:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///../../components/App.tsx (22:85)
../../components/App.tsx
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (2532:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///./index.tsx (55:92)
./index.tsx
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4358:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
webpack-internal:///./entry.js (54:83)
./entry.js
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (4347:0)
__nested_webpack_require_9336666__
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5625:0)
<unknown>
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5889:55)
<unknown>
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (5892:10)
<unknown>
webpackUniversalModuleDefinition@webpack-internal:///./node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (11:20)
<unknown>
node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js (18:1)
./node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js
file:/an-codeAI/.next/static/chunks/components_components_Whiteboard_tsx.js (27:1)
options.factory
file:/an-codeAI/.next/static/chunks/webpack.js (707:31)
__webpack_require__
file:/an-codeAI/.next/static/chunks/webpack.js (37:33)
fn
file:/an-codeAI/.next/static/chunks/webpack.js (362:21)
<unknown>
node_modules/@excalidraw/excalidraw/main.js (10:2)
./node_modules/@excalidraw/excalidraw/main.js
file:/an-codeAI/.next/static/chunks/components_components_Whiteboard_tsx.js (37:1)
options.factory
file:/an-codeAI/.next/static/chunks/webpack.js (707:31)
__webpack_require__
file:/an-codeAI/.next/static/chunks/webpack.js (37:33)
fn
file:/an-codeAI/.next/static/chunks/webpack.js (362:21)
<unknown>
webpack-internal:///./components/components/Whiteboard.tsx (7:99)
./components/components/Whiteboard.tsx
file:/an-codeAI/.next/static/chunks/components_components_Whiteboard_tsx.js (64:1)
options.factory
file:/an-codeAI/.next/static/chunks/webpack.js (707:31)
__webpack_require__
file:/an-codeAI/.next/static/chunks/webpack.js (37:33)
fn
file:/an-codeAI/.next/static/chunks/webpack.js (362:21)

**Comment by sparrow-js** [comment]
fixed, excalidraw fixed to 0.17.2 or Upgrade yourself.

**Comment by HakaishinShwet** [comment]
@sparrow-js thanks, btw pretty nice project keep it up :-))
