### ISSUE TITLE
使用Gemini报错

### ISSUE THREAD

**Issue by lovelyqun** [sparrow-js/an-codeAI#87]
![image](https://github.com/sparrow-js/an-codeAI/assets/25495741/05709620-09c2-42c6-bbc3-5160eff4a6e7)

**Comment by sparrow-js** [comment]
google 接口估计有调整请求不通，晚点看看适配下

**Comment by sparrow-js** [comment]
Error: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer

**Comment by sparrow-js** [comment]
Gemini 生成效果太差，已删除对Gemini支持
