### ISSUE TITLE
运行部起来，报错啊

### ISSUE THREAD

**Issue by zyfyh8023** [sparrow-js/an-codeAI#88]
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x7ffeeb20fd30

**Comment by z2labplus** [comment]
Unhandled Runtime Error
ChunkLoadError: Loading chunk vendor failed. (error: http://localhost:3000/excalidraw-assets-dev/vendor-39727f4653a274cf18f6.js)

**Comment by sparrow-js** [comment]
修改下 excalidraw 版本
