### ISSUE TITLE
 openAI request error!

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [sparrow-js/an-codeAI#93]
根据给的 api key 和 proxy url，在线上网站的设置，OpenAI API key 里填入，上传图片后，报  openAI request error!

**Comment by nuonuonuonuoyan** [comment]
![image](https://github.com/sparrow-js/an-codeAI/assets/41810021/08af70f4-3c25-49fa-9b1e-2d73c66397c8)
终端报的错是这个

**Comment by sparrow-js** [comment]
你的邮箱是哪个，之前的模型报错了，提供下邮箱我给你改下

boyang ***@***.***> 于2024年6月18日周二 15:24写道：

**Comment by sparrow-js** [comment]
openAI model 已经改到 4o
